USE TestDB
--SELECT
--	Name,
--	Gender,
--	Salary,
--	ROW_NUMBER() OVER (ORDER BY Gender) AS RowNumber
--FROM Employees WITH (NOLOCK)

--SELECT
--	Name,
--	Gender,
--	Salary,
--	ROW_NUMBER() OVER (PARTITION BY Gender ORDER BY Gender) AS RowNumber
--FROM Employees WITH (NOLOCK)

SELECT * FROM Employees

--DELETE ALL DUPLICATE ROWS EXCEPT ONE
--NOTE THIS WILL DELETE FROM THE UNDERLYING TABLE NOT CTE
WITH EmployeesCTE AS
(
   SELECT *, ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID) AS RowNumber
   FROM Employees
)

DELETE FROM EmployeesCTE WHERE RowNumber > 1

SELECT * FROM Employees